### ISSUE TITLE
cannot export my Illustrator file as an SVG

### ISSUE THREAD

**Issue by DD-A-YAN** [newsdev/ai2html#102]
Why I cannot export my Illustrator file as an SVG?

When I change the settings block to image_format:svg, it trun wrong.

The Script Was Unable to Finish
Error
================
• RuntimeError on line 3353: null is not an object

================
ai2html-nyt5 v0.76.0

**Comment by mbloch** [comment]
I just published v0.76.1, which should fix this error.
