### ISSUE TITLE
Error ================ • RuntimeError on line 1208: an Illustrator error occurred: 1346458189 ('MRAP')

### ISSUE THREAD

**Issue by DD-A-YAN** [newsdev/ai2html#104]
when I run the script, it turn wrong.

The Script Was Unable to Finish.
Error
================
• RuntimeError on line 1208: an Illustrator error occurred: 1346458189 ('MRAP')

================
ai2html-nyt5 v0.76.1

**Comment by mbloch** [comment]
Hi,
In my experience, MRAP errors occur intermittently and without a clear cause. When an MRAP error occurs, restarting Illustrator generally solves the problem. If you receive the error repeatedly in the same place, please help me investigate by emailing me a copy of your .ai file, so I can replicate the issue.

**Comment by DD-A-YAN** [comment]
Thanks! I have solved the problem through your answer.
