### ISSUE TITLE
Should we add white-space:nowrap on point type objects?

### ISSUE THREAD

**Issue by archietse** [newsdev/ai2html#11]
This would prevent inadvertent wrapping of point text at the edge of your artboard. This happens because text may be longer in a browser than in Illustrator because of font rendering differences.

The downside of this is that text that is too long will be hidden.

Not sure which way to go on this.

**Comment by mbloch** [comment]
Commit 6891f6d1cb11e6b21fd30da969244f0b10fb4e08 adds white-space:nowrap to all point-type text frames. Previously, this style was added only to transformed text frames.

If someone wants to place point text right against the edge of the artboard and is worried about running over, then they can use either right or left justification to make sure that the text expands away from the edge of the graphic.
