### ISSUE TITLE
html center does not with max with

### ISSUE THREAD

**Issue by szeemi** [newsdev/ai2html#119]
html center does not with max with

Hi there,

I'm unable to center the html if I add a max with value. 

Tamas

**Comment by mbloch** [comment]
Hi @szeemi, can you attach the files for an example HTML page that shows this problem, to help me investigate?

**Comment by szeemi** [comment]
Hi Matthew,

This is what I get (attached) if I add "max_width: 1000" to the settings.

best

Tamas

**Comment by kevinschaul** [comment]
@mbloch @szeemi This gist demonstrates the issue: https://gist.github.com/kevinschaul/2b0e5c80c92493842a12b2551ea5245f

Apologies that the image doesn't come through (and I'm unsure how to attach the .ai file either, but I'm happy to provide both if needed via email).

We've been using the fix I submitted in #121.
