### ISSUE TITLE
Error when creating config file

### ISSUE THREAD

**Issue by sondrn** [newsdev/ai2html#120]
I´m trying to use set the `create_config_file`-option.

ai2html-config.json:

`{
  "create_config_file": true,
  "config_file_path": "./config.yml"
}`

I've tried putting other objects, such as `fonts`, `image_output_path`into the json array, and it works well, but when I set `"create_config_file": true`, I get this error, and the config-file is not created.

<img width="422" alt="Skjermbilde 2019-08-19 kl  20 42 40" src="https://user-images.githubusercontent.com/6030145/63290583-fe27ab00-c2c1-11e9-8cff-bc26ca79a293.png">

Ai2html-version: 0.91.2
AI-version: 2019

**Comment by mbloch** [comment]
Hi @sondrn,
Thanks for the bug report. I released a new version of ai2html this morning (v0.92.0) that should fix this problem.

**Comment by sondrn** [comment]
Awesome!
