### ISSUE TITLE
Fixed responsiveness artboards behaving like dynamic

### ISSUE THREAD

**Issue by wmandrews** [newsdev/ai2html#122]
This commit has fixed artboards, but the map bg image is scaling as if it's dynamic, causing a height overflow issue.
https://preview.nyt.net/preview/2019-08-27-fires-embed-new/628f72e/

Later commits were just changed to dynamic since it works well that way. But maybe a bug?

**Comment by mbloch** [comment]
This should be fixed in v0.94.0
