### ISSUE TITLE
responsiveness: dynamic causes max_width 1600 every time

### ISSUE THREAD

**Issue by wmandrews** [newsdev/ai2html#123]

**Comment by mbloch** [comment]
I haven't been able to reproduce this. A max_width setting in the ai2html settings text block seems to override the default 1600px value. Can you give a bit more context to help troubleshoot this?

**Comment by wmandrews** [comment]
Here's an example ai2html project. 
https://preview.nyt.net/preview/2019-09-09-ai2html-test/master/

`max_width: 600` set in the ai. config.yml always ends up as 1600 after running ai2html.

**Comment by mbloch** [comment]
I understand the issue now, it's fixed in v0.94.1
