### ISSUE TITLE
Specifying artboard custom breakpoint and responsiveness doesn't work

### ISSUE THREAD

**Issue by kevinschaul** [newsdev/ai2html#124]
With an artboard name of `small:600:fixed`, I would expect the artboard's custom breakpoint to be set at 600 and its responsiveness to be set to fixed. This does not seem to be working in my testing.

I think this is related to the `parseObjectName()` function, which seems to get hung up when the artboard name contains multiple colons:

`parseObjectName('small:600:fixed')`
=> `{ "600:fixed": true }`

I would expect this to return `{ "width": 600, "fixed" true }`.

**Comment by mbloch** [comment]
The way it works now is, you use a single colon followed by comma-delimited parameters. So you would go: `small:600,fixed`

**Comment by kevinschaul** [comment]
Ah, check that out! Thanks for the help.
