### ISSUE TITLE
Wrap everything in a <html> line

### ISSUE THREAD

**Issue by garibaldig** [newsdev/ai2html#133]
Hi all,
I was trying to move around the order of things when exporting the .html file.

The idea is to have this order here:
```
1. <html>
2. <all the generated code by the script>
3. </html>
```

Thank you so much

**Comment by martgnz** [comment]
It could be an option in the settings too (I had to add it too). Did you manage to do it? As a reference I managed to do it by adding the tags between [these lines](https://github.com/newsdev/ai2html/blob/master/ai2html.js#L4126-L4134):

```js
if (scriptEnvironment == 'nyt-preview') {
  commentBlock += '<!-- preview: ' + settings.preview_slug + ' -->\r';
}
if (settings.scoop_slug_from_config_yml) {
  commentBlock += '<!-- scoop: ' + settings.scoop_slug_from_config_yml + ' -->\r';
}

// add html tags
commentBlock += '<html lang="en">\r';
commentBlock += '<head>\r';
commentBlock += '\t<meta charset="utf-8">\r';
commentBlock += '\t<meta name="viewport" content="width=device-width">\r';
commentBlock += '</head>\r';
commentBlock += '<body>\r';

// HTML
html = '<div id="' + containerId + '" class="ai2html">\r';
```

And then I replaced the [textForFile](https://github.com/newsdev/ai2html/blob/master/ai2html.js#L4154-L4155) declaration with this:

```js
textForFile =  '\r' + commentBlock + css + '\r' + html + '\r' + js +
"</body>\r" +
"</html>\r" +
"<!-- End ai2html" + " - " + getDateTimeStamp() + " -->\r";
```

**Comment by garibaldig** [comment]
Fantastic @martgnz !

Thank you so much again for your help, much appreciated it!
