### ISSUE TITLE
Idea: Set an explicit pixel width for text boxes

### ISSUE THREAD

**Issue by wmandrews** [newsdev/ai2html#159]
We'd like to try keeping text blocks from scaling on dynamic responsiveness files. One idea is to set an explicit pixel width on the text boxes without scaling them. Is there a field we could add to ai2html-settings to control this?

**Comment by mbloch** [comment]
I added an optional setting, "text_responsiveness".  You can set it to "responsive" (the default) or "fixed". Note that this applies to area text only... AI point text is always fixed. This update will be included in v0.119.0.
