### ISSUE TITLE
"text_responsiveness: fixed" dialog warning; help docs

### ISSUE THREAD

**Issue by briantjacobs** [newsdev/ai2html#168]
When using `text_responsiveness: fixed` within the ai2html-settings box, running ai2html leads to a dialog with this warning
```
Settings block contains an unused parameter: text_responsiveness
```
Regardless, I have text placed as area text in my ai file and it respects the setting

Also, in the docs here http://ai2html.org/ it makes reference to a "responsive" default that's not listed as possible values:

```
text_responsiveness
    Possible values: fixed dynamic
    Default: responsive
```

**Comment by mbloch** [comment]
The warning and the docs are fixed in v0.120.2. Thanks :)
