### ISSUE TITLE
Bug: Majority bold text

### ISSUE THREAD

**Issue by jonhuang** [newsdev/ai2html#169]
Discovered this during the refactor.

If the majority of the text is bolded, the default paragraph basestyle is bolded as well. However, there is no `font-weight: normal` specified in the "Rules for converting AI fonts to CSS" so this causes all text to be bold. This probably applies to italics as well. 

will fix in refactor by forcing the basestyle to ignore these attributes.

**Comment by mbloch** [comment]
This affected fonts that were configured with `"weight":""`  for normal the regular weight in the list of ai-to-css font conversion rules, like "Arial". Fixed in 0.122.1. Thanks!
