### ISSUE TITLE
Factor out the parser

### ISSUE THREAD

**Issue by stevenvachon** [newsdev/ai2html#2]
to another library (preferably an npm package) so that other libraries can use it and to single out that feature for community involvement.

I had wanted to write an ai2svg library a while back and may still need to. Using your parser would save me a lot of trouble.

**Comment by archietse** [comment]
This is on my to do list. Am planning to start with an ai text to archieml export but will eventually expand that later to json that will contain text formatting attributes of each paragraph.

**Comment by stevenvachon** [comment]
+1

**Comment by mbloch** [comment]
Hi @stevenvachon,

You mentioned being interested in an ai2svg library... did you envision something that would parse .ai files directly, without having to run Illustrator? ai2html uses Illustrator's internal JavaScript API to read the contents of Illustrator documents, which means running Illustrator. That's probably not going to change.

I think that Archie was suggesting that ai2html switch to a two-step translation: first convert native Illustrator objects to an intermediate format internally, then convert this internal format  to one or another output formats (e.g. HTML or JSON).

For conversion to SVG, Illustrator's own export function seems to work well.

Do you want more control over how SVG gets exported than what Illustrator gives you?

**Comment by stevenvachon** [comment]
@mbloch I'd hoped to not depend on Illustrator. Accurate SVG output is fine, as cleanup can be performed with [svgo](https://npmjs.com/svgo).

**Comment by mbloch** [comment]
@stevenvachon It looks like ai2html is always going to depend on Illustrator for .ai file parsing and SVG export. We're not going to be able to remove that dependency...

**Comment by stevenvachon** [comment]
Ok, thank you.
