### ISSUE TITLE
This text is filled with non-RGB color

### ISSUE THREAD

**Issue by kumarharsh** [newsdev/ai2html#28]
This script keeps throwing these warnings when I'm using swatches I've defined (which are really just RGB colours).

**Comment by mbloch** [comment]
Hi, if you are still seeing these warnings, could you email me a sample document containing some text that triggers the problem? I haven't been able to replicate it. Also, what version of Illustrator are you using?
Thanks :)

**Comment by kumarharsh** [comment]
Hi, I am not using illustrator actively any more, but at that time, I was using CC 2015.

**Comment by mbloch** [comment]
Thanks for writing back, and I'm sorry that we weren't keeping up with GitHub issues for a while!

Even though I wasn't able to replicate this exact problem, I've made some changes that should help identify the problem if this crops up again.

The warning messages now display both the content of the affected text objects and the name of the unsupported fill type (e.g. GradientColor, CMYKColor). This will help to troubleshoot the problem if other people run into it. This update is included in ai2html-beta.js and will be included in the v0.64 release.
