### ISSUE TITLE
Override html text output on a per-artboard basis

### ISSUE THREAD

**Issue by dwtkns** [newsdev/ai2html#34]
Especially for mobile sizes on short deadlines, it would sometimes be preferable to just have a flag that bakes all text into a responsive image instead of worrying about alignment, text wrapping, etc.

**Comment by mbloch** [comment]
I added this feature by way of an optional annotation appended to the artboard name, which is consistent with how we are currently annotating artboard width. Example:
`Artboard 1:image_only`
You would specify multiple artboard-specific settings like this:
`Artboard 1:600,image_only`  (to specify 600px breakpoint width and set the `image_only` flag).
