### ISSUE TITLE
Clickable Links

### ISSUE THREAD

**Issue by luscafontoura** [newsdev/ai2html#41]
Is there anyway to make just some text layers clickable? Something like "click here" and the hyperlink in the word? 

By the way, awesome tool!

**Comment by dwtkns** [comment]
It can get a bit messy, but you can use regular HTML in your Illustrator text block:

In AI:
![image](https://cloud.githubusercontent.com/assets/1456378/23753504/bb78fa0a-04a7-11e7-87d3-02a61451c857.png)

In the browser:
![image](https://cloud.githubusercontent.com/assets/1456378/23753494/b11be25c-04a7-11e7-83e8-c29ac6594580.png)
