### ISSUE TITLE
text fields containing '$'

### ISSUE THREAD

**Issue by jrmychrstphr** [newsdev/ai2html#43]
Exporting artwork with text elements that contain a dollar sign ($) character appear to have a bug, unless the text element ONLY contains the character.

The problem seems to remove the dollar sign character AND the very next character in the string, but not affect any other content.

I can resolve the issue by manually replacing each instance of '$' to `'&dollar;'`, but am hoping there is a better way to fix it, without manual editting of text inside the .ai file.

[I've set up a page showcasing the problem here.](http://nuk-sto-editorial-prod-staticassets.s3.amazonaws.com/SundayTimesGraphics/github-examples/YYYMMDD_TEST_DOLLARSIGN_TEST/ai2html-output/DOLLARSIGN.preview.html)

Here's how each artboard in the .ai file that page is out put from looks:
![image](https://cloud.githubusercontent.com/assets/1871741/18952493/bded9762-8641-11e6-8aa3-d40e53edf346.png)

Any help would be hugely appreciated.

**Comment by mbloch** [comment]
This issue is fixed in [ai2html-beta.js](https://github.com/newsdev/ai2html/blob/ceb0706d00a38f327d8cde330a62430c61747945/ai2html-beta.js). The fix will be included in the upcoming 0.64 release.
