### ISSUE TITLE
Resizer Script Incorrectly Included 

### ISSUE THREAD

**Issue by 1wheel** [newsdev/ai2html#45]
This config block incorrectly includes the resizer script, even though `include_resizer_css_js`is set to false: 

		ai2html-settings
		settings_version: 0.60
		create_promo_image: yes
		project_name: ai2swiper
		image_format: jpg
		write_image_files: yes
		responsiveness: dynamic
		html_output_path: ../src/slides/
		image_output_path: ../../public/_assets/
		use_lazy_loader: no
		include_resizer_classes: no
		iinclude_resizer_css_js: no
		include_resizer_script: no
		include_resizer_widths: no
		max_width: 
		output: multiple-files
		png_number_of_colors: 128
		jpg_quality: 60
		show_completion_dialog_box: true
		last_updated_text: 
		headline: 
		leadin: 
		summary: 
		notes: 
		sources: 
		credit: By The New York Times
		page_template: nyt5-article-embed
		show_in_compatible_apps: yes
		display_for_promotion_only: false
		constrain_width_to_text_column: false

It looks like something is overriding `included_resizer_css_js` to `yes`:
 
![image](https://cloud.githubusercontent.com/assets/1643998/20018061/a0e61d66-a29c-11e6-9e07-35625651ab74.png)

Blanking out `responsiveJS` in script fixed the issue for this project, but that breaks all resizing:  

		if (docSettings.include_resizer_script=="yes") {
			responsiveJs = '\t' + getResizerScript() + '\n';
			responsiveCss             = "";
		}
		responsiveJs        = "";

Moving the resizer settings to the end of the config also fix the issue: 

		ai2html-settings
		settings_version: 0.60
		create_promo_image: yes
		project_name: ai2swiper
		image_format: jpg
		write_image_files: yes
		responsiveness: dynamic
		html_output_path: ../src/slides/
		image_output_path: ../../public/_assets/
		max_width: 
		output: multiple-files
		png_number_of_colors: 128
		jpg_quality: 60
		show_completion_dialog_box: true
		last_updated_text: 
		headline: 
		leadin: 
		summary: 
		notes: 
		sources: 
		credit: By The New York Times
		page_template: nyt5-article-embed
		show_in_compatible_apps: yes
		display_for_promotion_only: false
		constrain_width_to_text_column: false
		use_lazy_loader: no
		include_resizer_css_js: no
		include_resizer_classes: no
		include_resizer_widths: no
		include_resizer_script: no

**Comment by mbloch** [comment]
This is fixed in the current beta version, closing.
