### ISSUE TITLE
Delicious URL has changed

### ISSUE THREAD

**Issue by travisricks** [newsdev/ai2html#48]
Hey NYT!

I just wanted to let you know the Delicious links on http://ai2html.org are no longer working. Looks like the new syntax is:
https://del.icio.us/archietse/ai2html,nyt

Thanks so much for this great script!

**Comment by dwtkns** [comment]
Seems like they're working now... though using a `,` instead of a `+` in the URL gives a different set of results and I can't tell why.

494 results:
https://del.icio.us/archietse/ai2html+nyt

139 results:
https://del.icio.us/archietse/ai2html,nyt
