### ISSUE TITLE
Error pasting text

### ISSUE THREAD

**Issue by giratikanon** [newsdev/ai2html#50]
Sometimes, after pasting text into the settings box, running ai2html causes a "can't paste type" error, presumably because of some special character or encoding issue: 

![image](https://cloud.githubusercontent.com/assets/333527/22214494/bf33f8d0-e165-11e6-823f-1d4e5a5e6f20.png)

![image](https://cloud.githubusercontent.com/assets/333527/22221131/9fca33e6-e17f-11e6-92a5-42f90554ad1c.png)

**Comment by giratikanon** [comment]
Steps to reproduce: 

1. `preview clone 2017-01-23-district-map`
2. Open the `ai/0125 web DISTRICTmap.ai` file in Illustrator
3. Copy and paste formatted text from an email (such as the meeting time in a Google Calendar reminder)
4. Paste it into the ai2html-settings as the summary or some other field
5. Run ai2html

**Comment by mbloch** [comment]
This error occurred when ai2html was run while a range of characters in a text object was selected. It is fixed in [ai2html-beta.js](https://github.com/newsdev/ai2html/blob/ceb0706d00a38f327d8cde330a62430c61747945/ai2html-beta.js).
