### ISSUE TITLE
Incorrect behavior when editing opacity mask

### ISSUE THREAD

**Issue by dwtkns** [newsdev/ai2html#61]
If you run ai2html while editing an opacity mask, the script behaves as though the contents of the mask **is** the graphic: ai2html creates a new settings block (within the mask), ignoring any that are in the "wider world" of the ai file outside the mask. If you run the script again, it renders the mask as your graphic.

This meshes intuitively with how AI itself handles edits to opacity masks: while you're in "Opacity Mask" edit mode, your layers panel is replaced with the objects that exist within the mask you're editing.

Hopefully there's a way to check whether the user is editing an opacity mask when the script is run.
This problem is similar to #35, relating to isolation mode.

**Comment by mbloch** [comment]
Added a check for this.
