### ISSUE TITLE
New York Times example in README isn't working

### ISSUE THREAD

**Issue by Cauchon** [newsdev/ai2html#74]
In the README for this GitHub:
> Here are **examples of how we’ve used the script** at The New York Times and examples of how others have used it. Share your ai2html projects on Twitter, Delicious, etc. using #ai2html.

The bolded link (https://del.icio.us/archietse/ai2html,nyt) seems to be dead.

Note: It's still broken in https://github.com/newsdev/ai2html/tree/readme-edits

**Comment by mbloch** [comment]
When I follow the link, I see a message saying the `del.icio.us` site will be back online on July 24... let's check again next week...

**Comment by mbloch** [comment]
The links in question seem to be working again...

**Comment by Spaxe** [comment]
Link is broken still.
