### ISSUE TITLE
ai2html-settings property to define prefixes for generated filenames

### ISSUE THREAD

**Issue by dwtkns** [newsdev/ai2html#8]
Would be useful in some situations to be able to decouple generated filenames from the filename of the parent AI file.

Right now an AI file with the filename `iraq-and-syria-maps-from-may-15.ai` and with artboards `big` and `small` will (with the `output:` property set to `multiple-files`) generate html files named:

`iraq-and-syria-maps-from-may-15-big.html`
`iraq-and-syria-maps-from-may-15-small.html`

It would be nice to be able to set something like `generated_files_prefix: maps` in the ai2html-settings block so that in this situation we can instead generate:

`maps-big.html`
`maps-small.html`

**Comment by mbloch** [comment]
The `project_name` setting does this...  looks like this issue can be closed.
