### ISSUE TITLE
Adding alt text to exported images

### ISSUE THREAD

**Issue by petulla** [newsdev/ai2html#94]
Hi there

Has there been any discussion around adding alt text to exported images? It could be a configurable field in the text block. This would help make ai2html more consistent with general accessibilty guidelines.

**Comment by mbloch** [comment]
I added an alt attribute to images in the just-published v0.79.0. The alt text is blank by default, or you can add an "image_alt_text" option to the setting block (or the still-undocumented "ai2html-config.json" file).
